### ISSUE TITLE
Add a WordPress backend solutions for dynamic content

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/code4.md#2]
### Data needed

<details>
<summary>Articles</summary>

- title
- rich body content
- category
</details>

<details>
<summary>Application</summary>

- title
- domain
- description
- image
- link app
- sponsors
- volunteers
- stage/status
</details>

<details>
<summary>Community</summary>

- name
- job title
- photo
- isStaff
- linkedin
- website
- weight
</details>

<details>
<summary>Sponsors</summary>

- photo
- URL
- name
- categories
</details>

### References

https://github.com/colbyfayock/next-wordpress-starter
https://api.code4.md/
https://github.com/aderaaij/wp-vercel-deploy-hooks
~https://wordpress.org/plugins/webhook-netlify-deploy/~

### About Vercel deploy

Vercel allows to add wehooks to rebuild your site when content has changed

![image](https://user-images.githubusercontent.com/1881266/103799760-32853e00-5054-11eb-9077-ff095d82f91e.png)

**Comment by unrevised6419** [comment]
Decided to integrate a Cloud Headless CMS that stores data in git
https://forestry.io/
